### ISSUE TITLE
Bug in Anki 23.10

### ISSUE THREAD

**Issue by guillem-palau-salva** [Toocanzs/anki-voicevox#3]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-06 20:57:11
Add-ons possibly involved: ⁨VOICEVOX Japanese Text To Speech Audio Generator⁩

Caught exception:
Traceback (most recent call last):
  File "...\addons21\366960193\__init__.py", line 6, in <lambda>
    menu.addAction("Generate VOICEVOX Audio", lambda: voicevox_gen.onVoicevoxOptionSelected(browser))
  File "...\addons21\366960193\voicevox_gen.py", line 304, in onVoicevoxOptionSelected
    dialog = MyDialog(browser)
  File "...\addons21\366960193\voicevox_gen.py", line 213, in __init__
    self.button_box.addButton("Cancel", qt.QDialogButtonBox.RejectRole)
AttributeError: type object 'QDialogButtonBox' has no attribute 'RejectRole'

**Comment by Toocanzs** [comment]
I've pushed a fix for this. Try updating and let me know if any other issues pop up.

**Comment by guillem-palau-salva** [comment]
Now it works. thank you for your prompt fix. Do you accept donations?

**Comment by Toocanzs** [comment]
Glad it's fixed. If you want to send me something, https://www.paypal.com/paypalme/toocanzs is the place to do it. Thanks.
