### ISSUE TITLE
How to customize the volume of generated audio?

### ISSUE THREAD

**Issue by hu3rror** [Toocanzs/anki-voicevox#4]
Hello,

I'm using anki-voicevox to generate audio clips and have noticed that the volume of all generated audio is quite low and soft.

I'm wondering if there's a way to customize the volume of the generated audio?

The ideal would be to have parameters that allow controlling the volume, e.g. to set it to a standard or higher volume level.

I've checked the documentation but haven't found any settings related to audio volume. I'm not sure if this is already supported? If not, could it be considered as a feature for future versions?

I would greatly appreciate any guidance on this! I've been using anki-voicevox's audio generation capabilities for a while and it has been incredibly helpful. 

Looking forward to your reply, thanks!

**Comment by Toocanzs** [comment]
I've just pushed an update add the ability to change volume, pitch, and speed. Give it a try
