### ISSUE TITLE
Can't generate audio

### ISSUE THREAD

**Issue by StevenH845** [Toocanzs/anki-voicevox#7]
I keep voicevox running, but I can't generate audio.

Error message as below:

```
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2024-06-17 22:15:37

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Roaming\Anki2\addons21\366960193\__init__.py", line 6, in <lambda>
    menu.addAction("Generate VOICEVOX Audio", lambda: voicevox_gen.onVoicevoxOptionSelected(browser))
  File "C:\Users\AppData\Roaming\Anki2\addons21\366960193\voicevox_gen.py", line 350, in onVoicevoxOptionSelected
    dialog = MyDialog(browser)
  File "C:\Users\AppData\Roaming\Anki2\addons21\366960193\voicevox_gen.py", line 97, in __init__
    common_fields = getCommonFields(self.selected_notes)
  File "C:\Users\AppData\Roaming\Anki2\addons21\366960193\voicevox_gen.py", line 29, in getCommonFields
    note = mw.col.get_note(note_id)
AttributeError: 'Collection' object has no attribute 'get_note'
```

**Comment by Toocanzs** [comment]
Unfortunately Anki has decided to deprecate a lot of the old ways of getting notes and updating notes, and after version 2.1.50 has removed the fallbacks that made older version work. 

These have been deprecated for at least 3 years and removed as of 2 years ago, so unfortunately I'm going to stick with the newer way of doing things. That means that the oldest supported version is 2.1.50. I've marked that as the minimum version on the AnkiWeb page. 

If you want this plugin to work, update to at least version 2.1.50

**Comment by Toocanzs** [comment]
Actually, even going up 1 version from the one you're on (2.1.44 -> 2.1.45) will solve this issue for you.

Sorry I would love to support all versions of Anki but they make it quite hard.
